name = "systemfd"
version = "0.1.0"
defaultTargets = ["systemfd"]

[[require]]
name = "lean-subst"
path = "lean-subst"

[[require]]
name = "lilac"
path = "lilac"

[[lean_lib]]
name = "Core"

[[lean_exe]]
name = "systemfd"
root = "Main"
