name = "systemfd"
version = "0.1.0"
defaultTargets = ["systemfd"]

[[require]]
name = "lean-subst"
scope = "amarmaduke"
git = "https://github.com/amarmaduke/lean-subst"
rev = "1a9097cc64ef751ee73e130c3dc544b869bd10b8"

[[require]]
name = "lilac"
scope = "amarmaduke"
git = "https://github.com/amarmaduke/lilac"
rev = "50e4bac0041514f121a726a85679986cfbb77cc2"

[[lean_lib]]
name = "Core"

[[lean_lib]]
name = "Surface"

[[lean_lib]]
name = "Translation"

# [[lean_lib]]
# name = "SystemFD"

[[lean_exe]]
name = "systemfd"
root = "Main"
